import argparse
from pathlib import Path

from pipeline import load_transcript_json, search_transcript, timestamp


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Search a Whisper transcript JSON.")
    parser.add_argument(
        "--transcript",
        required=True,
        help="Path to JSON transcript generated by run_stt.py",
    )
    parser.add_argument(
        "--query",
        help="Search keyword or text. If omitted, interactive prompt is used.",
    )
    parser.add_argument(
        "--min-score",
        type=float,
        default=0.8,
        help="Minimum score threshold for a segment to match.",
    )
    parser.add_argument(
        "--limit",
        type=int,
        default=20,
        help="Maximum number of matches to print.",
    )
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    transcript_path = Path(args.transcript)
    payload = load_transcript_json(transcript_path)

    query = args.query or input("Enter keyword/text to search: ").strip()
    if not query:
        raise ValueError("Query cannot be empty.")

    matches = search_transcript(
        transcript_payload=payload,
        query=query,
        min_score=args.min_score,
        limit=args.limit,
    )

    print(f"\nTranscript: {transcript_path}")
    print(f"Query: {query}")
    print(f"Matches: {len(matches)}\n")

    if not matches:
        print("No matches found. Try a lower --min-score (for example 0.65).")
        return

    for idx, item in enumerate(matches, 1):
        start = timestamp(item["start"])
        end = timestamp(item["end"])
        print(f"{idx:02d}. [{start} -> {end}] score={item['score']}")
        print(f"    {item['text']}")


if __name__ == "__main__":
    main()